name: Deploy Flask Backend to ECS
on:
  push:
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Log in to Amazon ECR
        run: aws ecr get-login-password | docker login --username AWS --password-stdin 851617285991.dkr.ecr.us-east-1.amazonaws.com

      - name: Build, tag, and push Docker image
        env:
          IMAGE_URI: 851617285991.dkr.ecr.us-east-1.amazonaws.com/backend-repo
        run: |
          docker build -f backend/Dockerfile -t $IMAGE_URI:latest backend
          docker push $IMAGE_URI:latest
