name: Destroy Terraform Infrastructure

on:
  workflow_dispatch:  # Manual trigger from GitHub Actions UI

jobs:
  destroy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init Terraform (Backend)
        run: terraform -chdir=terraform/backend init

      - name: Destroy Backend Infrastructure
        run: terraform -chdir=terraform/backend destroy -auto-approve

  destroy-frontend:
    runs-on: ubuntu-latest
    needs: destroy-backend  # ensure backend is destroyed first

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init Terraform (Frontend)
        run: terraform -chdir=terraform/frontend init

      - name: Destroy Frontend Infrastructure
        run: terraform -chdir=terraform/frontend destroy -auto-approve
